import Head from "next/head";
import Button from "../components/common/Button";
import Hero from "../components/home/Hero";
import Nav from "../components/home/Nav";

export default function Home() {
  return (
    <div>
      <Head>
        <title>my fantastic website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{position:"relative"}}>
        <Nav/>
        <Hero />
        {/* <Technologies/> */}
        {/* <Experience/> */}
        {/* <Contact/> */}
      </main>

      {/* <Footer/> */}
      <footer></footer>
    </div>
  );
}
